set DIE_HEIGHT 3200
set DIE_WIDTH 3200
set DESIGN_NAME fpga_core
set TASK_NAME FPGA1212_QLSOFA_CHD_task
set VERILOG_PROJ_DIR FPGA1212_QLSOFA_CHD_Verilog
set FPGA_ROW 12
set FPGA_COL 12
set INIT_DESIGN_INPUT ASCII
set TECHNOLOGY skywater
set DP_BLOCK_REFS [list ];
set DP_FLOW "hier";
set DESIGN_STYLE "hier";
set STANDARD_CELLS sc_hd;
