#############################################
#	Synopsys Design Constraints (SDC)
#	For FPGA fabric 
#	Description: Disable routing multiplexer outputs for PnR
#	Author: Xifan TANG 
#	Organization: University of Utah 
#	Date: Tue Dec  8 15:34:14 2020
#############################################

set_disable_timing fpga_core_uut/cbx_*__*_/mux_top_ipin_*/out
set_disable_timing fpga_core_uut/cbx_*__*_/mux_top_ipin_*/out
set_disable_timing fpga_core_uut/cbx_*__*_/mux_bottom_ipin_*/out
set_disable_timing fpga_core_uut/cbx_*__*_/mux_top_ipin_*/out
set_disable_timing fpga_core_uut/cby_*__*_/mux_right_ipin_*/out
set_disable_timing fpga_core_uut/cby_*__*_/mux_right_ipin_*/out
set_disable_timing fpga_core_uut/cby_*__*_/mux_left_ipin_*/out
set_disable_timing fpga_core_uut/cby_*__*_/mux_right_ipin_*/out
set_disable_timing fpga_core_uut/cbx_*__*_/mux_top_ipin_*/out
set_disable_timing fpga_core_uut/cbx_*__*_/mux_top_ipin_*/out
set_disable_timing fpga_core_uut/cby_*__*_/mux_right_ipin_*/out
set_disable_timing fpga_core_uut/cby_*__*_/mux_right_ipin_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_top_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_right_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_bottom_track_*/out
set_disable_timing fpga_core_uut/sb_*__*_/mux_left_track_*/out
set_disable_timing fpga_core_uut/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mux_fabric_out_*/out
set_disable_timing fpga_core_uut/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/mux_frac_logic_out_*/out
set_disable_timing fpga_core_uut/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/mux_frac_lut*_*_in_*/out
set_disable_timing fpga_core_uut/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mux_ff_*_D_*/out
